In [1]:
# functions age_process(age): This function categorizes age into groups.
# It first checks if the age string is longer than 4 characters to avoid processing empty or invalid ages.
# It then splits the age string (assuming it's in a format like "40-50") and takes the first part.
# The age is categorized into 4 groups:
   # 1: Under 40
   # 2: 40-59
   # 3: 60-79
   # 4: 80 and above
# If the age string is invalid or empty, it returns None.
def age_process(age):
    if len(str(age))>4:
        num=int(age.split('-')[0].strip())
        if num<40:
            return 1
        elif num<60:
            return 2
        elif num<80:
            return 3
        return 4
    return


#PCODE_AREA_process(code): This function categorizes postal code areas.
#It checks the first character of the postal code.
#If it's 'C', 'P', 'S', or 'I', it returns that character.
#For any other character, it returns 'other'.
#Note: The last line return code is unreachable and should probably be removed.
def PCODE_AREA_process(code):
    if code[0] in ['C','P','S','I']:
        return code[0]
    return 'other'
    return code[0]


#ETHNICITY_process(ethnicity): This function simplifies ethnicity categorization.
#If the ethnicity is 'A' (majority of the population), it returns 'A'.
#For any other ethnicity, it returns 'other'.
def ETHNICITY_process(ethnicity):
    if ethnicity=='A':
        return 'A'
    else:
        return 'other'

In [2]:
import pandas as pd
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

# 1.Loading Data:
data_all=pd.read_excel('/Users/r.h.wang/Documents/Mst HD/0. Disso Writing/Analytics/30Oct_final/data_all.xlsx',sheet_name='Sheet1')
data_feature=pd.read_excel('/Users/r.h.wang/Documents/Mst HD/0. Disso Writing/Analytics/Python/page snomed code.xlsx',sheet_name='feature')

# 2.Selecting Features:
   #Selects features marked as 'used' in the feature sheet.
   #Creates a new DataFrame data_analysis with only these selected features.   
features=data_feature[data_feature['used']==1]['name'].values.tolist()
data_analysis=data_all[features]
data_feature=pd.read_excel('/Users/r.h.wang/Documents/Mst HD/0. Disso Writing/Analytics/Python/page snomed code.xlsx',sheet_name='feature')

# 3.Selecting Features:Identifying Symptoms and Comorbidities:Creates a list of symptoms and comorbidities from the feature sheet.
SymptomsComorbidities=data_feature[data_feature['SymptomsComorbidities']==1]['name'].values.tolist()

# 4.Processing Symptoms and Comorbidities:
   #Iterates through each row and symptom/comorbidity.
   #If the value's length is > 4, sets it to 1 (present), otherwise 0 (absent).
for index,row in tqdm(data_analysis.iterrows()):
    for item in SymptomsComorbidities:
        if len(str(row[item]))>4:
            data_analysis.loc[index, item]=1
        else:
            data_analysis.loc[index, item]=0

# 5.Applying Data Processing Functions:
#Applies the previously defined functions (age_process, PCODE_AREA_process, ETHNICITY_process) to their respective columns.
data_analysis['AGE_GRP_AT_ADM'] = data_analysis.apply(lambda x: age_process(x.AGE_GRP_AT_ADM), axis=1)
data_analysis['PCODE_AREA'] = data_analysis.apply(lambda x: PCODE_AREA_process(x.PCODE_AREA), axis=1)
data_analysis['ETHNICITY'] = data_analysis.apply(lambda x: ETHNICITY_process(x.ETHNICITY), axis=1)
data_analysis.to_excel('/Users/r.h.wang/Documents/Mst HD/0. Disso Writing/Analytics/30Oct_final/data_analysis.xlsx',index=False)
data_analysis

1730it [00:02, 725.64it/s]

,PATIENTID,GENDER,PCODE_AREA,ETHNICITY,DOD,CANCER,cardiovascular_adminID_num,DEAD,covid,adminID,...,Cancer,Heart valve disorder,Fatigue,Cough,Vomiting,Nausea,Headache,ITU_num,ITU_hour,BMI
0,D1917A064ADE19D601DF43DF4AC0EDB40C8B2E143CD06A...,1,C,A,34600.0,Y,1,1,0,3F43772988AD82E2D2FD50E9C3EB251DA4E8253B564E25...,...,0,0,0,0,0,0,0,0,0.0,0
1,A51387C9064B83E379CF58B48B1D6935262F7B950C51D5...,1,P,A,NaN,N,1,0,0,E4AA425EC2879B4FD021A18840F774D29A9B0D916AC932...,...,0,0,0,0,0,0,0,0,0.0,0
2,6CD89B9487B66816F10BA35B5C398605DF0B9BFD5C2FA0...,1,C,A,36472.0,Y,4,1,1,EB9794A6AD9DCEA69A8F8D18161BAE4A474F07C5C2DE47...,...,0,0,0,0,0,0,0,0,0.0,0
3,0A91111CB6E0008C8519E366DADFB95CD21249080280E6...,1,P,A,NaN,N,1,0,0,58DA88A9BA349E014B4C8B32EFB607F87FFF34F286D40A...,...,0,0,0,0,0,0,0,0,0.0,0
4,5ED4DB0EF402CFA869F9B5C8779EDCE193982E9D2B87AD...,1,C,other,29155.0,N,1,1,0,E5874F09AD7E5302BEB0754862C2D956FC52E07BE2849A...,...,0,0,0,0,0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1725,2B2DC2C477620D9F109B76DF0FBF89D3EBA71169EDA6B9...,2,C,A,25195.0,Y,7,1,1,A31B4EA3D308DE7B645D2DEC7629BA904B86AA84C8B3E4...,...,0,0,0,0,0,0,0,0,0.0,0
1726,07D96DC81E62CE5427EC0E569D87CFF3BC1CE9C67AD5D2...,1,C,A,21296.0,N,1,1,0,75296F309875068EB8E67D84C0D07096E9B15CBF1069DD...,...,0,0,0,0,0,0,0,0,0.0,0
1727,9555EF433E379D50AA57DBEE581ED61B1012274C90B3B7...,1,S,A,NaN,Y,1,0,0,8EB068666E188DE523A1BE74E995D31E17181DD1041B13...,...,0,0,0,0,0,0,0,0,0.0,0
1728,597228D385F35DDA9F26685D61BC7DA28F08F749F275A5...,1,C,other,NaN,Y,7,0,0,94A29E441BFDF53DD565EA0F396BE48BFF3FC3C562EBF4...,...,0,0,0,0,0,0,0,0,0.0,0
1729,164BB7E179FAC24D1FB12BA1291F2E10CBA36A48680838...,2,C,other,NaN,N,1,0,0,62FDF283FFC374BA961D612C732D4BCE086E8BC62DC90E...,...,0,1,0,0,0,0,0,0,0.0,0

In [9]:
data_analysis['PCODE_AREA'].value_counts()

C        1165
P         200
S         159
other     122
I          84
Name: PCODE_AREA, dtype: int64